theme = "catppuccin_macchiato"

[keys.normal]
"A-z" = ":toggle soft-wrap.enable"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-s" = ":write"

[keys.normal."["]
b = ":buffer-previous"

[keys.normal."]"]
b = ":buffer-next"

[keys.insert]
"C-s" = ["normal_mode", ":write"]

[keys.normal.space]
q = { q = ":quit-all", w = ":quit" }
"|" = ":vsplit"
"-" = ":hsplit"

[editor.soft-wrap]
enable = true
max-wrap = 25        # maximum free space left on the right side
max-indent-retain = 40
wrap-indicator = "↪ " # indicator shown at the start of wrapped lines
