theme = "catppuccin_macchiato"

[keys.normal]
"A-z" = ":toggle soft-wrap.enable"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

[keys.normal.space]
q = { q = ":quit-all" }

[editor.soft-wrap]
enable = true
max-wrap = 25        # maximum free space left on the right side
max-indent-retain = 40
wrap-indicator = "↪ " # indicator shown at the start of wrapped lines
