theme = "catppuccin_macchiato"

[keys.normal]
"A-z" = ":toggle soft-wrap.enable"

[editor.soft-wrap]
enable = true
max-wrap = 25        # maximum free space left on the right side
max-indent-retain = 40
wrap-indicator = "↪ " # indicator shown at the start of wrapped lines
